#[path = "src/command_names.rs"]
mod command_names;

fn remove_stale_e2e_permissions() {
    // tauri-build writes generated command permissions into the source tree and
    // does not remove permissions produced by an earlier feature-enabled build.
    // If an E2E build and a release build share a checkout, those stale files
    // would otherwise be embedded in the release ACL manifest even though the
    // corresponding Rust handlers are correctly compiled out.
    let permissions_dir = std::path::Path::new("permissions/autogenerated");
    let Ok(entries) = std::fs::read_dir(permissions_dir) else {
        return;
    };

    for entry in entries.flatten() {
        let path = entry.path();
        let is_e2e_permission = path
            .file_name()
            .and_then(|name| name.to_str())
            .is_some_and(|name| name.starts_with("e2e_") && name.ends_with(".toml"));

        if is_e2e_permission {
            std::fs::remove_file(&path).unwrap_or_else(|error| {
                panic!(
                    "failed to remove stale E2E permission {}: {error}",
                    path.display()
                )
            });
        }
    }
}

fn main() {
    // `AppManifest::commands` stores the slice for `'static`, so each branch
    // must yield a `'static` slice. The base list already is; the e2e list is
    // concatenated and leaked (harmless in a short-lived build script).
    //
    // The `e2e` feature exposes test-only IPC shims. Generate their ACL
    // permissions only for that build so a release binary never carries them.
    // Cargo exposes enabled features to build scripts as `CARGO_FEATURE_<NAME>`.
    let e2e_enabled = std::env::var_os("CARGO_FEATURE_E2E").is_some();
    if !e2e_enabled {
        remove_stale_e2e_permissions();
    }

    let commands: &'static [&'static str] = if e2e_enabled {
        let mut all: Vec<&'static str> = command_names::APP_COMMANDS.to_vec();
        all.extend_from_slice(command_names::E2E_COMMANDS);
        Box::leak(all.into_boxed_slice())
    } else {
        command_names::APP_COMMANDS
    };

    let manifest = tauri_build::AppManifest::new().commands(commands);
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(manifest))
        .expect("failed to build Tauri application metadata");
}
